version: '3.8'

services:
  db:
    container_name: pg_container
    image: postgres:13.11
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/home/pg_database/

volumes:
  pg_data: