apiVersion: v1
kind: Service
metadata:
  name: service-nginx-multitool
spec:
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: 80
    - name: multitool
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: deployment