---
all:
  hosts:
    sonar-01:
      ansible_name: "root"
      ansible_host: 51.250.0.59
      ansible_private_key_file: /home/baryshnikov/.ssh/id_rsa
    nexus-01:
      ansible_name: "root"
      ansible_host: 51.250.88.48
      ansible_private_key_file: /home/baryshnikov/.ssh/id_rsa
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: baryshnikov