apiVersion: v1
kind: Service
metadata:
  name: service-nginx-multitool
  namespace: application-configuration
spec:
  type: NodePort
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30000
    - name: multitool
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
  selector:
    app: deployment