apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-nginx
  namespace: networking-in-k8s-part1
spec:
  ports:
    - name: nginx
      port: 9001
      protocol: TCP
      targetPort: 80
      nodePort: 30000
  selector:
    app: deployment
  type: NodePort