apiVersion: v1
kind: Service
metadata:
  name: service-nginx-multitool
  namespace: networking-in-k8s-part1
spec:
  ports:
    - name: nginx
      port: 9001
      protocol: TCP
      targetPort: 80
    - name: multitool
      port: 9002
      protocol: TCP
      targetPort: 8080
  selector:
    app: deployment