apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nginx
  namespace: application-configuration
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>This is a configMap Index file</h1>
    </html>