apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: network-in-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool