apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  namespace: app
spec:
  ports:
    - name: multitool
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: front