FROM centos:7

MAINTAINER BaryshnikovNV <Baryshnikov.nv@gmail.com>

ENV PATH=/usr/lib:/elasticsearch-7.17.14/jdk/bin:/elasticsearch-7.17.14/bin:$PATH

RUN yum install wget -y && \
    yum install perl-Digest-SHA -y

RUN wget --quiet https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.14-linux-x86_64.tar.gz && \
    wget --quiet https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.14-linux-x86_64.tar.gz.sha512 && \
    sha512sum --check --quiet elasticsearch-7.17.14-linux-x86_64.tar.gz.sha512 && \
    tar -xzf elasticsearch-7.17.14-linux-x86_64.tar.gz && \
    rm elasticsearch-7.17.14-linux-x86_64.tar.gz && \
    rm elasticsearch-7.17.14-linux-x86_64.tar.gz.sha512

ENV ES_HOME=/elasticsearch-7.17.14

RUN groupadd -g 1000 elasticsearch && useradd elasticsearch -u 1000 -g 1000

RUN mkdir /var/lib/elasticsearch

WORKDIR /var/lib/elasticsearch

RUN set -ex && for path in data logs config config/scripts; do \
        mkdir -p "$path"; \
        chown -R elasticsearch:elasticsearch "$path"; \
    done

RUN mkdir /elasticsearch-7.17.14/snapshots && \
    chown -R elasticsearch:elasticsearch /elasticsearch-7.17.14

COPY logging.yml /elasticsearch-7.17.14/config/
COPY elasticsearch.yml /elasticsearch-7.17.14/config/

USER elasticsearch

CMD ["elasticsearch"]

EXPOSE 9200 9300