apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-busybox-multitool
  namespace: storage-in-k8s-part-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: busybox
          image: busybox:1.36.1
          command: ['sh', '-c', 'while true; do date >> /opt/date.log; sleep 5; done']
          volumeMounts:
            - name: data
              mountPath: "/opt"
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: data
              mountPath: "/test"