version: '3.8'

services:
  db:
    container_name: pg_container
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/home/pg_database/
      - pg_backup:/home/pg_backup/

volumes:
  pg_data:
  pg_backup: